language: node_js
sudo: false
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_94eb0650f8ed_key -iv $encrypted_94eb0650f8ed_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- chmod 600 .travis/id_rsa
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
after_success:
- ember build
- scp -o StrictHostKeyChecking=no -i .travis/id_rsa -r ./dist/* bttf@chewbonga.com:/home/bttf/screenwritr/dist
